# -*- coding: utf-8 -*-
"""hw_3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pudkRYYWUNzz2giZCUGTbTcMOy4Wa3mA
"""

prime_numbers = 0

def primer(x):
    if x >= 2:
        for y in range(2,x):
            if not ( x % y ):
                return False
    else:
      return False
    return True



for i in range(0,101):
    if primer(i):
        prime_numbers += 1
        print(i)

#print("We found " + str(prime_numbers) + " prime numbers.")