# -*- coding: utf-8 -*-
"""hw_4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Am6PxlV9aCzgl076wLhIW0jwHbDFU2TY
"""

class Animals:
    def __init__(self, name, color):
        self.name = name
        self.color = color


    def animals_style(self):
        print("Özellikler")


class Dogs:
    def __init__(self, name, color):
        self.name = name
        self.color = color

    def animals_style(self):
        print("Özellikler")


class Cats:
    def __init__(self, name, color):
        self.name = name
        self.color = color

    def animals_style(self):
        print("Özellikler")



class Style:
    def __init__(self, name, color):
        print("Özellikler")
        self.name = name
        self.color = color
        

    def animals_style(self):
        print("Özellikler")



class Animals(Style):
    pass
class Dogs(Style):
    pass
class Cats(Style):
    pass



animals = Animals("Hayvan","Renk")
dogs = Dogs("Çoban","Siyah")
cats = Cats("Tekir","Beyaz")

print("Animals")
print(animals.name)
print(animals.color)


print("Dogs")
print(dogs.name)
print(dogs.color)


print("Cats")
print(cats.name)
print(cats.color)